<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQwCpglw\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQwCpglw/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQwCpglw.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQwCpglw\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQwCpglw\appAppKernelProdContainer([
    'container.build_hash' => 'QwCpglw',
    'container.build_id' => 'e51a1931',
    'container.build_time' => 1710886476,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQwCpglw');
