<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnBuFSn\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnBuFSn/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerKnBuFSn.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerKnBuFSn\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerKnBuFSn\appAppKernelProdContainer([
    'container.build_hash' => 'KnBuFSn',
    'container.build_id' => 'd3b7bb5a',
    'container.build_time' => 1710875064,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnBuFSn');
