<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKX6wUVx\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKX6wUVx/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerKX6wUVx.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerKX6wUVx\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerKX6wUVx\appAppKernelProdContainer([
    'container.build_hash' => 'KX6wUVx',
    'container.build_id' => 'a0d602f7',
    'container.build_time' => 1710883321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKX6wUVx');
