version: "3"
services:
  web:
    build: ../apache
    env_file:
      - ../.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ../apache/exemplo.lan.conf:/etc/apache2/sites-enabled/exemplo.lan.conf
      - ../apache/certificados:/certificados
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  datos:
