<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3n93lcs\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3n93lcs/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container3n93lcs.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container3n93lcs\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container3n93lcs\appAppKernelProdContainer([
    'container.build_hash' => '3n93lcs',
    'container.build_id' => '00fa5675',
    'container.build_time' => 1710880502,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3n93lcs');
