<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWtSXJS\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWtSXJS/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXWtSXJS.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXWtSXJS\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXWtSXJS\appAppKernelProdContainer([
    'container.build_hash' => 'XWtSXJS',
    'container.build_id' => 'e2896427',
    'container.build_time' => 1710884025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWtSXJS');
