version: "3"
services:
  web:
    image: nginx:latest
    env_file:
      - ../.env
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./app:/app
      - ../nginx/certificados:/certificados
      - ../nginx/exemplo.lan.conf:/etc/nginx/templates/exemplo.lan.conf.template
  php:
    build: ../php
    volumes:
      - ./app:/app
      - ../php/www.conf:/etc/php/8.2/fpm/pool.d/www.conf

  db:
    image: mysql:8.3
    ports:
      - 3307:3306
    restart: always
    env_file:
      - ./.env_bd
    volumes:
      - ./bd/backup:/docker-entrypoint-initdb.d
      - datos:/var/lib/mysql
volumes:
  datos:
