<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLutk1Fl\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLutk1Fl/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLutk1Fl.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLutk1Fl\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLutk1Fl\appAppKernelProdContainer([
    'container.build_hash' => 'Lutk1Fl',
    'container.build_id' => 'bf3a4873',
    'container.build_time' => 1710695479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLutk1Fl');
