<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPEUcNTa\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPEUcNTa/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPEUcNTa.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPEUcNTa\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPEUcNTa\appAppKernelProdContainer([
    'container.build_hash' => 'PEUcNTa',
    'container.build_id' => 'b7d2dc3c',
    'container.build_time' => 1710198586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPEUcNTa');
